### ISSUE TITLE
[Feature Request] - More Ethereum Layer 2 blockchain support

### ISSUE THREAD

**Issue by ffrediani** [etherfi-protocol/smart-contracts#200]
Please consider supporting other Layer 2 EVM Networks (Polygon, Arbitrum or Base) for staking LBTC and WBTC, specially LBTC from Lombard. Transaction fees are insane on Ethereum and prevents users from doing more BTC staking in Ether.fi. Gas is high most of the time.

Particularly depositing LBTC from Lombard if they start to mint on any of these blockchains allows users to enjoy much lower fees, plus there is a possibility to deposit also WBTC and cbBTC from these networks. For their existing BSC support it is limited because it only works for when depositing with BTCB.

Please engage Lombard directly to align which would be the Layer 2 choice to start with, but add any.

At the moment Ethereum is quiet expensive and every transaction (Approve, Stake, Unstake, Transfer) is a real waste of money in transaction fees.

**Comment by jtfirek** [comment]
Hey, we are working towards deploying native minting for eBTC to {base, corn} rn! Deployment should be mid to late December

**Comment by ffrediani** [comment]
Hello @jtfirek thanks for the clarification.

Good to know that Base is to be supported soon. I understand that will work for both accepting deposits of WBTC, LBTC, FBBTC and cbBTC as also to receive eBTC, correct ?

For LBTC in specific Lombard doesn't mint it on Base. If possible please engage them that you are going that path so the entire path can work for those who use both platforms.

Regarding other more popular L2 any thoughts on Arbitrum or Polygon after Base ?

**Comment by jtfirek** [comment]
Hello, we are live on base, arb, and corn! WBTC, LBTC, and cbBTC are deposit assets, but LBTC is not supported!
